### ISSUE TITLE
Does not work with https urls !

### ISSUE THREAD

**Issue by Abdullah-F** [tkellen/rack-slashenforce#2]
when i provide a link without a trailing slash and the request is https it directs to port 80 instead of the default  port of https protocol !

**Comment by western** [comment]
Code of rack-slashenforce is proto-independent. If you start use https - your result is https, not http. If you start is http - your result is http.

**Comment by Abdullah-F** [comment]
when i type an https link in the browser with a trailing slash it works fine , but when i type https link without a trailing slash it redirects to port 80 !
